# Generated by Django 3.2 on 2021-04-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('label', models.CharField(blank=True, help_text='Overrides the display name in the structure mode.', max_length=255, verbose_name='Label')),
                ('column_width', models.CharField(blank=True, choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five'), ('six', 'six'), ('seven', 'seven'), ('eight', 'eight'), ('nine', 'nine'), ('ten', 'ten'), ('eleven', 'eleven'), ('twelve', 'twelve'), ('thirteen', 'thirteen'), ('fourteen', 'fourteen'), ('fiveteen', 'fiveteen'), ('sixteen', 'sixteen')], max_length=20, verbose_name='Number Columns')),
                ('align', models.CharField(blank=True, choices=[('left floated', 'Left floated'), ('center aligned', 'Center aligned'), ('right floated', 'Right floated')], max_length=20, verbose_name='type_group')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_semantic_ui_column', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('label', models.CharField(blank=True, help_text='Overrides the display name in the structure mode.', max_length=255, verbose_name='Label')),
                ('type_container', models.CharField(blank=True, choices=[('left aligned', 'Left aligned'), ('center aligned', 'Center aligned'), ('right aligned', 'Right aligned'), ('justified', 'Justified')], max_length=20, verbose_name='type_group')),
                ('is_text_container', models.BooleanField(default=False, help_text='Check if this is a text container', verbose_name='Text container')),
                ('is_raised', models.BooleanField(default=False, help_text='Check if this is a raised container', verbose_name='Raised container')),
                ('is_fluid', models.BooleanField(default=False, help_text='Check if this is a Fluid container', verbose_name='Fluid container')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_semantic_ui_container', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('label', models.CharField(blank=True, help_text='Overrides the display name in the structure mode.', max_length=255, verbose_name='Label')),
                ('number_columns', models.CharField(blank=True, choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five'), ('six', 'six'), ('seven', 'seven'), ('eight', 'eight'), ('nine', 'nine'), ('ten', 'ten'), ('eleven', 'eleven'), ('twelve', 'twelve'), ('thirteen', 'thirteen'), ('fourteen', 'fourteen'), ('fiveteen', 'fiveteen'), ('sixteen', 'sixteen')], max_length=20, verbose_name='Number Columns')),
                ('grid_type', models.CharField(blank=True, choices=[('relaxed', 'relaxed'), ('internally celled', 'Internally celled'), ('equal width', 'Equal width')], max_length=20, verbose_name='Grid Type')),
                ('align', models.CharField(blank=True, choices=[('left aligned', 'Left aligned'), ('centered', 'Centered'), ('right aligned', 'Right aligned')], max_length=20, verbose_name='type_group')),
                ('responsive', models.CharField(blank=True, choices=[('stackable', 'Stackable'), ('doubling', 'Doubling'), ('stackable doubling', 'Stackable and Doubling')], help_text='Grid responsive behavior', max_length=20, null=True, verbose_name='Responsive')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_semantic_ui_grid', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='GroupSegment',
            fields=[
                ('label', models.CharField(blank=True, help_text='Overrides the display name in the structure mode.', max_length=255, verbose_name='Label')),
                ('type_group', models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='vertical', max_length=20, verbose_name='type_group')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_semantic_ui_groupsegment', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('label', models.CharField(blank=True, help_text='Overrides the display name in the structure mode.', max_length=255, verbose_name='Label')),
                ('color', models.CharField(blank=True, choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('olive', 'Olive'), ('green', 'Green'), ('teal', 'Teal'), ('blue', 'Blue'), ('violet', 'Violet'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey'), ('black', 'Black')], help_text='Color Segment', max_length=20, null=True, verbose_name='Color')),
                ('inverted_color', models.BooleanField(default=False, help_text='Inveted Color Segment', verbose_name='Inverted Color')),
                ('type_segment', models.CharField(blank=True, choices=[('raised', 'Raised'), ('stacked', 'Stacked'), ('tall stacked', 'Tall stacked'), ('piled', 'Piled')], help_text='Whats the type of segment', max_length=20, null=True, verbose_name='Type')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_semantic_ui_segment', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('label', models.CharField(blank=True, help_text='Overrides the display name in the structure mode.', max_length=255, verbose_name='Label')),
                ('data_tab', models.CharField(help_text='Data_tab', max_length=255, verbose_name='Datatab')),
                ('tab_type', models.CharField(blank=True, choices=[('bottom attached', 'Bottom attached')], default='bottom attached', max_length=20, verbose_name='Tab Type')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_semantic_ui_tab', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TabContainer',
            fields=[
                ('label', models.CharField(blank=True, help_text='Overrides the display name in the structure mode.', max_length=255, verbose_name='Label')),
                ('tab_container_type', models.CharField(blank=True, choices=[('top attached tabular', 'Top attached tabular'), ('pointing secondary', 'Pointing secondary')], default='top attached tabular', max_length=20, verbose_name='Tab Container Type')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_semantic_ui_tabcontainer', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
