# Generated by Django 3.2 on 2021-04-21 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_semantic_ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('label', models.CharField(blank=True, help_text='Overrides the display name in the structure mode.', max_length=255, verbose_name='Label')),
                ('header', models.CharField(help_text='Name of an user', max_length=255, verbose_name='Header (Name)')),
                ('company_position', models.CharField(max_length=255, verbose_name='Position in the company')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('description', models.CharField(blank=True, help_text='Short description', max_length=255, null=True, verbose_name='Description')),
                ('right_bottom_content', models.CharField(help_text='Additional content displayed in right bottom corner of the card', max_length=32, verbose_name='Right bottom content')),
                ('color', models.CharField(blank=True, choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('olive', 'Olive'), ('green', 'Green'), ('teal', 'Teal'), ('blue', 'Blue'), ('violet', 'Violet'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('grey', 'Grey'), ('black', 'Black')], help_text='Color Segment', max_length=20, null=True, verbose_name='Color')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_semantic_ui_card', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='CardContainer',
            fields=[
                ('label', models.CharField(blank=True, help_text='Overrides the display name in the structure mode.', max_length=255, verbose_name='Label')),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_semantic_ui_cardcontainer', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
